relative_dir = "../Data/GDSC_DATASET_S1-S12/"

table_1 = "Table_S1_GDSC_Gene_expression.csv"
table_2 = "Table_S2_GDSC_Methylation.csv"
table_3 = "Table_S3_GDSC_Mutation.csv"
table_4 = "Table_S4_GDSC_Copy_number_variation.csv"
table_5 = "Table_S5_GDSC_Cell_line_annotation.csv"
table_6 = "Table_S6_GDSC_Drug_response_IC50.csv"
table_7 = "Table_S7_GDSC_Drug_response_AUC.csv"
table_8 = "Table_S8_GDSC_Protein-protein_interaction_network.csv"
table_9 = "Table_S9_GDSC_Drug_structural_features_fingerprints.xlsx"
table_10 = "Table_S10_GDSC_Drug_similarities.csv"
table_11 = "Table_S11_GDSC_Gene_group.csv"
table_14 = "Table_S12_GDSC_Drug_group.csv"
